// <auto-generated />
using GamesZone.Data.ApplicationDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GamesZone.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GamesZone.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 3,
                            Name = "RPG"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Simulation"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Strategy"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Sports"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Puzzle"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Idle"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Casual"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Arcade"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Racing"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Shooter"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Fighting"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Survival"
                        },
                        new
                        {
                            Id = 16,
                            Name = "MMO"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Battle Royale"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Tower Defense"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Card"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Music"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Educational"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Trivia"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Board"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Word"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Casino"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Rhythm"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Poker"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Idle"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Simulation"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Strategy"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Sports"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Puzzle"
                        });
                });

            modelBuilder.Entity("GamesZone.Models.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Devices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Icon = "fas fa-desktop",
                            Name = "PC"
                        },
                        new
                        {
                            Id = 2,
                            Icon = "fab fa-playstation",
                            Name = "PlayStation"
                        },
                        new
                        {
                            Id = 3,
                            Icon = "fab fa-xbox",
                            Name = "Xbox"
                        },
                        new
                        {
                            Id = 4,
                            Icon = "fas fa-gamepad",
                            Name = "Nintendo"
                        });
                });

            modelBuilder.Entity("GamesZone.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Cover")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2500)
                        .HasColumnType("nvarchar(2500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("GamesZone.Models.GameDevice", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.HasKey("GameId", "DeviceId");

                    b.HasIndex("DeviceId");

                    b.ToTable("GameDevices");
                });

            modelBuilder.Entity("GamesZone.Models.Game", b =>
                {
                    b.HasOne("GamesZone.Models.Category", "Category")
                        .WithMany("Games")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("GamesZone.Models.GameDevice", b =>
                {
                    b.HasOne("GamesZone.Models.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamesZone.Models.Game", "Game")
                        .WithMany("Devices")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("GamesZone.Models.Category", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("GamesZone.Models.Game", b =>
                {
                    b.Navigation("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
